name: weather-check
on:
  schedule:
    - cron: "30 13 * * 1-5"
  workflow_dispatch:
jobs:
  checkWeather:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: run
        env:
          DISCORD: ${{ secrets.DISCORD_URL }}
          API: ${{ secrets.WEATHER_API_KEY }}
        run: |
          python ./main.py --discord=$DISCORD --api=$API
